version: 2

jobs:
  main:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox codecov
      - run: tox -e flake8,coverage
      - run: codecov --token=d84070ff-f638-4632-91c4-437ca7d45e2e
  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e py36
  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e py37

workflows:
  version: 2
  build:
    jobs:
      - main
      - py36:
          requires:
            - main
      - py37:
          requires:
            - main